//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formulario.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user
    {
        public int id { get; set; }
        public string primer_nombre { get; set; }
        public string otros_nombres { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public string documento { get; set; }
        public string celular { get; set; }
        public string correo { get; set; }
        public int ciudad { get; set; }
        public int departamento { get; set; }
    
        public virtual tb_ciudad tb_ciudad { get; set; }
        public virtual tb_departamento tb_departamento { get; set; }
    }
}
